FROM node:24-alpine

ARG NODE_ENV
ARG PORT
ARG CORS_ORIGIN
ARG JWT_SECRET
ARG JWT_ISSUER
ARG JWT_AUDIENCE
ARG REFRESH_TOKEN_SECRET
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_NAME
ARG BREVO_API_KEY
ARG DEFAULT_SENDER_EMAIL
ARG DEFAULT_SENDER_NAME
ARG CONTACT_EMAIL
ARG TURNSTILE_SECRET_KEY

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV CORS_ORIGIN=$CORS_ORIGIN
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_ISSUER=$JWT_ISSUER
ENV JWT_AUDIENCE=$JWT_AUDIENCE
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_NAME=$DATABASE_NAME
ENV BREVO_API_KEY=$BREVO_API_KEY
ENV DEFAULT_SENDER_EMAIL=$DEFAULT_SENDER_EMAIL
ENV DEFAULT_SENDER_NAME=$DEFAULT_SENDER_NAME
ENV CONTACT_EMAIL=$CONTACT_EMAIL
ENV TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["node", "dist/main.js"]