FROM node:24-alpine

# Application configuration
ARG NODE_ENV
ARG PORT
ARG CORS_ORIGIN

# Database configuration
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_POOL_SIZE
ARG DB_POOL_MIN_SIZE
ARG DB_IDLE_TIMEOUT
ARG DB_CONNECTION_TIMEOUT
ARG DB_ACQUIRE_TIMEOUT

# JWT configuration
ARG JWT_SECRET
ARG JWT_ISSUER
ARG JWT_AUDIENCE
ARG JWT_ACCESS_TOKEN_TTL
ARG REFRESH_TOKEN_SECRET
ARG JWT_REFRESH_TOKEN_TTL

# Email configuration
ARG BREVO_API_KEY
ARG DEFAULT_SENDER_EMAIL
ARG DEFAULT_SENDER_NAME
ARG CONTACT_EMAIL

# Security configuration
ARG TURNSTILE_SECRET_KEY
ARG BCRYPT_SALT_ROUNDS

# Rate limiting configuration
ARG THROTTLE_TTL
ARG THROTTLE_LIMIT
ARG SENSITIVE_THROTTLE_TTL
ARG SENSITIVE_THROTTLE_LIMIT

# Application configuration
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV CORS_ORIGIN=$CORS_ORIGIN

# Database configuration
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV DB_POOL_SIZE=$DB_POOL_SIZE
ENV DB_POOL_MIN_SIZE=$DB_POOL_MIN_SIZE
ENV DB_IDLE_TIMEOUT=$DB_IDLE_TIMEOUT
ENV DB_CONNECTION_TIMEOUT=$DB_CONNECTION_TIMEOUT
ENV DB_ACQUIRE_TIMEOUT=$DB_ACQUIRE_TIMEOUT

# JWT configuration
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_ISSUER=$JWT_ISSUER
ENV JWT_AUDIENCE=$JWT_AUDIENCE
ENV JWT_ACCESS_TOKEN_TTL=$JWT_ACCESS_TOKEN_TTL
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
ENV JWT_REFRESH_TOKEN_TTL=$JWT_REFRESH_TOKEN_TTL

# Email configuration
ENV BREVO_API_KEY=$BREVO_API_KEY
ENV DEFAULT_SENDER_EMAIL=$DEFAULT_SENDER_EMAIL
ENV DEFAULT_SENDER_NAME=$DEFAULT_SENDER_NAME
ENV CONTACT_EMAIL=$CONTACT_EMAIL

# Security configuration
ENV TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY
ENV BCRYPT_SALT_ROUNDS=$BCRYPT_SALT_ROUNDS

# Rate limiting configuration
ENV THROTTLE_TTL=$THROTTLE_TTL
ENV THROTTLE_LIMIT=$THROTTLE_LIMIT
ENV SENSITIVE_THROTTLE_TTL=$SENSITIVE_THROTTLE_TTL
ENV SENSITIVE_THROTTLE_LIMIT=$SENSITIVE_THROTTLE_LIMIT

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["node", "dist/main.js"]